version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/api
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command:
      - /bin/bash
      - -ce
      - |
        for i in 1 1 2 0; do
          /api/scripts/migrate.sh && break || sleep "$$i"
        done
        
        exec /api/scripts/run_server.sh